
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learningenglish?useSSL=false&serverTimezone=UTC
    password: 543682
    username: kientran
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
api:
  prefix: api
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
